### ISSUE TITLE
Any chance we can increase the timeout?

### ISSUE THREAD

**Issue by afharo** [uvejota/python-edata#15]
Hi!

Thank you for your work! I really like bringing my consumption stats down to Home Assistant.

The last data available in Home Assistant is from March 7. I've checked and Datadis has data until yesterday.

Whenever I login to Datadis' UI, it takes really long to load my suppliers (I think it's caused by a rogue and very old contract I've got with Iberdrola). 

Whenever I run it on Postman, it takes between 20s and 2 minutes 30s 😱 But it always succeeds.

I wonder if it makes sense to bump the timeout to give it more room for success.

It should be just bumping this number, right?

https://github.com/uvejota/python-edata/blob/5674348a1b8dfc0ed80436d632184afc210d96f6/edata/connectors/datadis.py#L44

This is what I see in the logs:

```
2023-03-29 17:26:04.704 WARNING (SyncWorker_1) [edata.connectors.datadis] Timeout at https://datadis.es/api-private/api/get-supplies
```

**Comment by afharo** [comment]
También podemos hablar en español si quieres... que siendo un servicio de España, no sé si tiene mucho sentido tratar esto en inglés 😅

**Comment by uvejota** [comment]
Hola, en la última versión lo he subido a 3 minutos, a ver si así te va mejor :)
